const QUESTIONS = {
  LOAD: 'QUESTIONS_LOAD',
  LOAD_SUCCESS: 'QUESTIONS_LOAD_SUCCESS',
  LOAD_FAIL: 'QUESTIONS_LOAD_FAIL',
};

const QUESTIONS_DETAILS = {
  LOAD: 'QUESTIONS_DETAILS_LOAD',
  LOAD_SUCCESS: 'QUESTIONS_DETAILS_LOAD_SUCCESS',
  LOAD_FAIL: 'QUESTIONS_DETAILS_LOAD_FAIL',
};

const ADD_QUESTION = {
  STORE_LOCALLY: 'ADD_QUESTION_STORE_LOCALLY',
  RESET: 'ADD_QUESTION_RESET',
  LOAD: 'ADD_QUESTION_LOAD',
  LOAD_SUCCESS: 'ADD_QUESTION_LOAD_SUCCESS',
  LOAD_FAIL: 'ADD_QUESTION_LOAD_FAIL',
};

export {
  QUESTIONS,
  QUESTIONS_DETAILS,
  ADD_QUESTION,
};
